version: "3.9"
services:
  nextjs-app:
    build: .
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env  
    volumes:
      # Mount source code in dev mode (uncomment for hot reload)
      # - .:/app
      # - /app/node_modules